using System.Text.Json;
using TelemetryApi.Models;

namespace TelemetryApi.Tests;

public class MachineReadingTests
{
    [Fact]
    public void MachineReading_HasAutoGeneratedId()
    {
        var reading = new MachineReading("machine-001", "temperature", 72.5, "celsius", "nominal", DateTime.UtcNow);
        Assert.NotEqual(Guid.Empty, reading.Id);
    }

    [Fact]
    public void MachineReading_TwoInstances_HaveDifferentIds()
    {
        var r1 = new MachineReading("machine-001", "temperature", 72.5, "celsius", "nominal", DateTime.UtcNow);
        var r2 = new MachineReading("machine-001", "temperature", 72.5, "celsius", "nominal", DateTime.UtcNow);
        Assert.NotEqual(r1.Id, r2.Id);
    }

    [Fact]
    public void MachineReading_SerializesToJson_WithAllProperties()
    {
        var reading = new MachineReading("machine-001", "temperature", 72.5, "celsius", "nominal", DateTime.UtcNow, "trace-abc");
        var json = JsonSerializer.Serialize(reading);
        Assert.Contains("machine-001", json);
        Assert.Contains("temperature", json);
        Assert.Contains("trace-abc", json);
    }

    [Fact]
    public void MachineReading_TraceId_DefaultsToNull()
    {
        var reading = new MachineReading("machine-001", "temperature", 72.5, "celsius", "nominal", DateTime.UtcNow);
        Assert.Null(reading.TraceId);
    }
}